enum Category { CAT, DOG, BUNNY, HAMSTER }
enum Condition { Adoption, Disappear, Mating }

class Pet {
  String name;
  String location;
  String condition;
  Category category;
  String imageUrl;
  bool viewFront;
  String sizePet;
  String weightPet;
  String pricePet;
  String expectancyLife;
  String description;

  Pet(
      this.name,
      this.location,
      this.condition,
      this.category,
      this.imageUrl,
      this.viewFront,
      this.sizePet,
      this.weightPet,
      this.pricePet,
      this.expectancyLife,
      this.description);
}

List<Pet> getPetList() {
  return <Pet>[
    Pet(
      "Abissínio",
      "Etiópia",
      "condition",
      Category.CAT,
      "assets/images/cats/abissinio.png",
      false,
      "20 cm - 40 cm",
      "4Kg - 7.5Kg",
      "De R\$ 1.000 a R\$ 2.000",
      "Varia de 10 a 15 anos",
      "Para quem quer ter um felino que seja leal e que fique perto do tutor em todos os momentos, o gato Abissínio é perfeito. Conhecido também como Aby, o bichano é uma das raças mais antigas de que se tem conhecimento. Por isso, é até difícil saber ao certo sua verdadeira origem. A raça de gato Abissínio tem muita energia e adora brincar, podendo ser até travessa. Não é difícil encontrar um gatinho desses em cima de uma prateleira ou dentro de um armário. Adoram ficar nas alturas para poder observar o ambiente e estar inteirado de tudo o que está acontecendo ao seu redor.",
    ),
    Pet(
      "Angorá turco",
      "Turquia",
      "condition",
      Category.CAT,
      "assets/images/cats/angora_turco.png",
      true,
      "40 cm - 60 cm",
      "3Kg - 8Kg",
      "De R\$ 3.000 a R\$ 10.000",
      "Varia de 12 a 18 anos",
      "O gato Angorá, em geral, é muito inteligente e conquista seu tutor com muita doçura e tranquilidade. Os felinos dessa raça têm muita energia e disposição para brincar, por isso adoram crianças. Ademais, eles são extremamente adaptáveis ao ambiente em que estão inseridos. Essa raça é uma das mais antigas do mundo, por isso é considerada um verdadeiro tesouro. O Angorá, apesar de ser dócil, tem a personalidade forte, e, geralmente, escolherá a pessoa que será seu tutor em seu lar. Uma vez escolhida, ele ficará totalmente apegado a ela, necessitando de muita atenção.",
    ),
    Pet(
      "Asiático de Pelo Semi-Longo",
      "Reino Unido",
      "condition",
      Category.CAT,
      "assets/images/cats/asiatico_de_pelo_semi_longo.png",
      true,
      "20 cm - 25 cm",
      "3,5Kg - 7Kg",
      "De R\$ 2.000 a R\$ 4.000",
      "Varia de 10 a 17 anos",
      "",
    ),
    Pet(
      "Azul Russo",
      "Rússia",
      "condition",
      Category.CAT,
      "assets/images/cats/azul_russo.png",
      false,
      "20 cm - 30 cm",
      "3Kg - 6Kg",
      "De R\$ 3.000 a R\$ 5.000",
      "Varia de 10 a 15 anos",
      "Conhecido também como “o tímido desconfiado”, o gato azul russo é, como o nome já indica, originário da Rússia, muito provavelmente da cidade portuária de Arkhangelsk e também da Escandinávia. Passou a ser levado para outras partes da Europa em 1860, tendo a Inglaterra como principal destino. Um gato afável e tímido, ele é muito sensível às emoções humanas e é muito bom em se entreter sozinho. Por ser um gato bastante tranquilo e independente, se dá bem com pessoas que moram sozinhas e idosos. Sua personalidade desconfiada e tímida faz com que não seja um bom companheiro para crianças, principalmente as que são mais agitadas, podendo se sentir intimidado e assustado.",
    ),
    Pet(
      "Balinês",
      "Estados Unidos",
      "condition",
      Category.CAT,
      "assets/images/cats/balines.png",
      false,
      "15 cm - 30 cm",
      "2,5Kg - 5Kg",
      "De R\$ 450 a R\$ 700",
      "Varia de 10 a 13 anos",
      "Pelos longos, finos e lisos: essas são as características mais comuns do gato Balinês. Facilmente confundido com o gato Siamês, o bichano desta raça também possui cores claras e manchas em determinados pontos do corpo e os olhos azuis marcantes. O companheirismo tem tudo a ver com a sua personalidade: além de se adaptar bem com mudanças, o gato Balinês é perfeito para quem busca um gatinho alegre e brincalhão.",
    ),
    Pet(
      "Bicolor Oriental",
      "Estados Unidos",
      "condition",
      Category.CAT,
      "assets/images/cats/bicolor_oriental.png",
      false,
      "20 cm - 40 cm",
      "4Kg - 6.5Kg",
      "De R\$ 400 a R\$ 1.000",
      "Varia de 13 a 14 anos",
      "O Oriental Shorthair é uma raça de gato doméstico, que está intimamente relacionado com o Siames. Ele mantém a cabeça e o corpo tipo do Siames moderno, mas aparece em uma ampla gama de cores e padrões de revestimento. Orientais são sociais, inteligentes e muitos são bastante vocais. De acordo com o perfil da raça CFA, “orientais representam um grupo diverso de gatos que têm o seu fundamento na raça siamês”. O Shorthair Oriental foi aceito como uma raça real nos EUA em 1977. Em 1985, o CFA reconheceu a variante bicolor. Duas décadas depois, a raça foi finalmente reconhecida pelo Reino Unido baseados no Conselho do Fantasia Gato (GCCF) em 1997, mas com algumas diferenças.",
    ),
    Pet(
      "Bobtail americano",
      "Estados Unidos",
      "condition",
      Category.CAT,
      "assets/images/cats/bobtail_americano.png",
      false,
      "30 cm - 50 cm",
      "3,6Kg - 6Kg",
      "De R\$ 1.300 a R\$ 3.000",
      "Varia de 11 a 15 anos",
      "Para cuidar de um American Bobtail, uma informação fundamental é que esses peludos amam se divertir. Se os tutores estiverem dispostos, o felino pode brincar de esconde-esconde ou de pegar a bolinha por horas sem cansar, inclusive chamando os membros da família para brincar com ele. Apesar disso, não é um gato que exige muitos exercícios físicos, mas pode ser treinado para passeios com guia acompanhando a família. Como é uma raça muito adaptável, eles também são ótimos companheiros para viagens e podem fazer parte de uma família mais caseira ou aventureira!",
    ),
    Pet(
      "Bombaim",
      "Estados Unidos",
      "condition",
      Category.CAT,
      "assets/images/cats/bombaim.png",
      false,
      "20 cm - 50 cm",
      "3,5Kg - 6Kg",
      "De R\$ 5.500 a R\$ 7.000",
      "Varia de 11 a 15 anos",
      "Gatos são conhecidos por sua independência física e emocional, no entanto, tutores de felinos sabem que a história nem sempre é assim. Isso acontece principalmente com o Bobtail americano, uma raça conhecida por sua doçura e companheirismo, além do seu charmoso rabinho de pom-pom. Com um coração bondoso e uma personalidade extrovertida, esse pet é ideal para tutores que buscam um companheiro para todas as horas. Sua formosura encanta a todos, inclusive outros bichinhos, que podem brincar e se divertir ao lado do felino.",
    ),
    Pet(
      "Burmilla",
      "Reino Unido",
      "condition",
      Category.CAT,
      "assets/images/cats/burmila.png",
      false,
      "20 cm - 50 cm",
      "4,5Kg - 6Kg",
      "De R\$ 1.000 a R\$ 2.000",
      "Varia de 10 a 16 anos",
      "O gato Burmilla é bastante raro, difícil de ser visto por aí. Surgiu na Grã-Bretanha como uma das raças de felinos mais novas, nascida em 1981. Mesmo com tanta jovialidade, ele é muito famoso, principalmente pela dificuldade de ser encontrado. Irreverente, o Burmilla gato tem um lado independente que o torna bastante tranquilo e sossegado. Porém, na maior parte do tempo, ele precisa receber atenção e trocar carinhos com os tutores.",
    ),
    Pet(
      "Exótico",
      "Estados Unidos",
      "condition",
      Category.CAT,
      "assets/images/cats/exotico.png",
      false,
      "20 cm - 50 cm",
      "3Kg - 7Kg",
      "De R\$ 1.000 a R\$ 5.000",
      "Varia de 8 a 15 anos",
      "O gato Exótico também é conhecido como Shorthair ou gato Exótico de pelo curto. Isso porque sua maior característica é ser muito parecido com a raça Persa. No entanto, tem uma diferença importante: seu pelo é bem curto e macio, semelhantemente ao de um urso de pelúcia. A raça gato Exótico de pelo curto é muito tranquila, fácil de conviver e tem uma natureza doce e amável. Por isso, é fácil cuidar desse felino, principalmente para quem mora em apartamento. Por não ser tão agitado, ele prefere viver em ambientes internos, mas, mesmo assim, consegue se adaptar com facilidade a qualquer local.",
    ),
    Pet(
      "Himalaio",
      "Nepal",
      "condition",
      Category.CAT,
      "assets/images/cats/himalaio.png",
      false,
      "20 cm - 50 cm",
      "4Kg - 6Kg",
      "De R\$ 2.000 a R\$ 5.000",
      "Varia de 9 a 15 anos",
      "Bastante tranquilo e parceiro, o gato Himalaio tem conquistado cada vez mais os tutores. O felino adora brincadeiras e esbanja energia por onde passa, além de ser carinhoso e se dar bem com todos à sua volta. Não à toa, é considerada uma das raças mais populares do mundo. Sua popularidade também está relacionada à personalidade dócil e gentil do gato Himalaio. O bichano adora estar próximo da sua família humana e, muitas vezes, prefere descansar próximo de seus tutores. Para completar, o Himalaio é inteligente e ama receber atenção.",
    ),
    Pet(
      "Maine Coon",
      "Estados Unidos",
      "condition",
      Category.CAT,
      "assets/images/cats/maine_coon.png",
      false,
      "20 cm - 50 cm",
      "4Kg - 8Kg",
      "De R\$ 3.000 a R\$ 7.000",
      "Varia de 10 a 15 anos",
      "Bastante charmoso, o Maine Coon chama a atenção por sua independência. Mesmo que o bichano adore passar algum tempo junto da sua família humana, é um gato que também desfruta de sua própria companhia. No entanto, graças à sua personalidade afetiva, ele vai gostar bastante de estar junto do tutor. De natureza dócil e gentil, o gato Maine Coon é considerado o felino mais antigo e tradicional da América. Com uma pelagem expressiva, a raça se destaca das demais por ser bastante resistente à água. Esse fato, inclusive, faz com que eles adorem brincar com o líquido.",
    ),
    Pet(
      "Pelo curto brasileiro",
      "Brasil",
      "condition",
      Category.CAT,
      "assets/images/cats/pelo_curto_brasileiro.png",
      false,
      "20 cm - 50 cm",
      "5Kg - 10Kg",
      "De R\$ 4.000 a R\$ 6.000",
      "Varia de 14 a 20 anos",
      "Considerada a única raça de gato do país, o gato de pelo curto brasileiro é o felino certo para quem busca um pet ágil e confiante, de personalidade lúdica e sociável. Para conhecer melhor essa raça, continue acompanhando o nosso guia! O porte médio, a pelagem curta e a aparência esbelta fazem da elegância uma das principais características do gato brasileiro. Seu desenvolvimento é atribuído ao engenheiro Paulo Samuel Ruschi, fundador da Federação Brasileira de Gatos.",
    ),
    Pet(
      "Pelo curto Europeu",
      "Suécia",
      "condition",
      Category.CAT,
      "assets/images/cats/pelo_curto_europeu.png",
      false,
      "15 cm - 20 cm",
      "3Kg - 6Kg",
      "De R\$ 7.500 a R\$ 10.000",
      "Varia de 10 a 15 anos",
      "O gato de pelo curto europeu é um felino extremamente doméstico, perfeito para famílias e também pessoas que moram sozinhas. Os laços que criam com seus tutores é surpreendente, tornando-os exímios companheiros para todas as horas. A inteligência desse animal chama bastante a atenção. Ele tem uma grande capacidade de aprendizado, seja na hora das brincadeiras ou dos treinamentos. Quer conhecer todas as características do gato europeu comum? Então, continue conosco e acompanhe cada detalhe!",
    ),
    Pet(
      "Persa",
      "Irã",
      "condition",
      Category.CAT,
      "assets/images/cats/persa.png",
      true,
      "20 cm - 50 cm",
      "3Kg - 7Kg",
      "De R\$ 2.000 a R\$ 3.000",
      "Varia de 10 a 15 anos",
      "Uma das características mais marcantes do gato Persa é, com certeza, sua pelagem extensa. Ela é solta, quase esvoaçante, e está por todo o corpo do animalzinho. Isso deixa o felino ainda mais fofo e charmoso. Os pelos de diferentes tonalidades contradizem o pequeno corpo do felino. Entre as condições que marcam o gato Persa estão sua cabeça bem redonda, cauda curta e avantajada, além dos olhos grandes. Isso sem falar nas pequenas orelhas com pontas redondas que aparecem em meio à pelagem.",
    ),
    Pet(
      "Ragdoll",
      "Estados Unidos",
      "condition",
      Category.CAT,
      "assets/images/cats/ragdoll.png",
      false,
      "20 cm - 50 cm",
      "3Kg - 7Kg",
      "De R\$ 5.000 a R\$ 10.500",
      "Varia de 10 a 15 anos",
      "Não é à toa que cada vez mais tutores tenham interesse em um gatinho feliz, carinhoso e super apegado à família. Claro que estamos falando do Ragdoll, um bichano de grande porte e pelagem fofinha, que tem feito muito sucesso entre os gateiros de plantão. Com todos esses atributos, fica fácil perceber que se trata de um excelente mascote.",
    ),
    Pet(
      "Sagrado da Birmânia",
      "Mianmar",
      "condition",
      Category.CAT,
      "assets/images/cats/sagrado_da_birmania.png",
      false,
      "20 cm - 50 cm",
      "3Kg - 3,5Kg",
      "De R\$ 450 a R\$ 700",
      "Varia de 10 a 15 anos",
      "O gato Birmânes envolve muitas lendas e mistérios em seu passado. Para explicar sua existência e suas cores incríveis, existe uma versão folclórica de tirar o fôlego. Se você quer conhecê-lo em detalhes, é melhor não perder uma só linha deste guia! Até porque quem não quer conhecer um gato Birmânes? Sua aparência exuberante, com pelos longos, chama a atenção por onde ele passa! O corpinho com marcações exclusivas é, com certeza, o grande diferencial da raça.",
    ),
    Pet(
      "Siamês",
      "Tailândia",
      "condition",
      Category.CAT,
      "assets/images/cats/siames.png",
      true,
      "20 cm - 30 cm",
      "2Kg - 6Kg",
      "De R\$ 500 a R\$ 1.000",
      "Varia de 15 a 20 anos",
      "Os gatos siameses são considerados gatos muito sociáveis e leais. Eles adoram brincar, são muito apegados aos humanos e procuram fazer parte das atividades diárias deles. Siameses adoram adultos, crianças - e conseguem acompanhar bem o ritmo delas, principalmente quando filhotes - e se dão bem com outros animais também. Eles gostam muito de atenção e por isso estão constantemente miando e pedindo por afagos. Os seus olhos de cor azul-safira são muito característicos da raça.",
    ),
    Pet(
      "Sphynx",
      "Canadá",
      "condition",
      Category.CAT,
      "assets/images/cats/sphynx.png",
      false,
      "20 cm - 50 cm",
      "3Kg - 7Kg",
      "De R\$ 2.000 a R\$ 5.000",
      "Varia de 8 a 14 anos",
      "Quem adora animais exóticos e diferentões com certeza tem muitas razões para se identificar com o Sphynx. O famoso gatinho sem pelos conquista cada vez mais tutores em todo o mundo, e por aqui não poderia ser diferente. Além de sua aparência única e encantadora, esse bichano possui tanta popularidade graças ao seu jeitinho dócil, carinhoso e cheio de companheirismo.",
    ),
    Pet(
      "Wirehair Americano",
      "Estados Unidos",
      "condition",
      Category.CAT,
      "assets/images/cats/wirehair_americano.png",
      false,
      "20 cm - 50 cm",
      "4Kg - 6Kg",
      "De R\$ 400 a R\$ 2.000",
      "Varia de 7 a 12 anos",
      "Está procurando por uma raça super adaptável, que conviva bem com pessoas de todas as idades e todo o tipo de ambiente? O American Wirehair é uma ótima opção! Esse peludinho pode se tornar um pet tão tranquilo na companhia de pessoas idosas quanto agitado com crianças. Um atleta felino por natureza, o gato americano de pelo áspero também é um forte aliado em relação à proteção da casa. Isso tudo graças ao seu grande carinho por sua família, que o faz prezar sempre pelo bem-estar dela.",
    ),
    Pet(
      "Afegão Hound",
      "Afeganistão",
      "condition",
      Category.DOG,
      "assets/images/dogs/afegao_hound.png",
      false,
      "63 cm - 74 cm",
      "23Kg - 30Kg",
      "De R\$ 1.200 a R\$ 2.000",
      "Varia de 10 a 14 anos",
      "Ele esbanja elegância com sua aparência exuberante e pelagem longa e sedosa, além disso, é bastante independente e seu perfil vigilante e corajoso o coloca como excelente defensor de território. Originários do atual Afeganistão, região de terras montanhosas, os cães dessa raça têm facilidade em se locomover em terrenos acidentados e têm instinto caçador considerável, já que foram criados para perseguir caça, como antílopes. É um excelente companheiro de caminhadas, porém, é difícil de treiná-lo, já que não é um exemplo de obediência. Como exige muito trabalho para manter a beleza de sua pelagem, além de campos abertos para correr e se exercitar - passeios com guia não proporcionam a eles o exercício necessário -, o Afghan Hound não é recomendado para principiantes.",
    ),
    Pet(
      "Affenpinscher",
      "Alemanha",
      "condition",
      Category.DOG,
      "assets/images/dogs/affenpinscher.png",
      false,
      "22 cm - 30 cm",
      "3Kg - 6Kg",
      "De R\$ 2.500 a R\$ 4.000",
      "Varia de 10 a 12 anos",
      "Um cão bastante brincalhão que adora se divertir e receber carinho: esse é o Affenpinscher! A aparência dele é exuberante e totalmente exótica, o que o diferencia de todas as outras raças. Esse cachorro está sempre alerta e pronto para estar com os tutores no que for preciso! Na França, o cão Affenpinscher é conhecido como “diabinho bigodudo”, mas isso não é por causa do seu comportamento, e sim pela aparência bagunçada. Ele gosta de uma agitação, porém não o tempo todo. O cachorrinho também adora ficar deitado no colo do seu tutor por horas, apenas sendo acariciado.",
    ),
    Pet(
      "Airedale Terrier",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/airedale_terrier.png",
      false,
      "56 cm - 61 cm",
      "18Kg - 25Kg",
      "De R\$ 1.000 a R\$ 2.000",
      "Varia de 10 a 13 anos",
      "Não é à toa que muitos entusiastas do mundo canino chamam o Airedale Terrier de rei dos Terriers. Considerado o cão mais alto dentre as demais raças desse grupo, o pet também é muito inteligente, brincalhão e ativo. Ele adora praticar esportes e atividades físicas. Sempre curioso, é um cão que pode tomar para si a posição de guarda da casa, mas que não esconde o apego pela família adotiva.",
    ),
    Pet(
      "Akita",
      "Japão",
      "condition",
      Category.DOG,
      "assets/images/dogs/akita.png",
      false,
      "23 cm - 28 cm",
      "30Kg - 60Kg",
      "De R\$ 1.500 a R\$ 3.000",
      "Varia de 10 a 12 anos",
      "Muito conhecido por sua aparência poderosa, o Akita Inu é um dos grandes nomes entre os cachorros que possuem a fidelidade aos seus tutores como característica principal. Não é à toa que a raça seja tão famosa e requisitada. Obstinado e tenaz, esse cachorro cheio de coragem tem tudo para conquistar sua família humana e é um excelente companheiro quando em boas mãos. Por isso, ao adotar, é fundamental ter em mente todos os cuidados e maneiras corretas de lidar com o animal.",
    ),
    Pet(
      "American Staffordshire Terrier",
      "Estados Unidos",
      "condition",
      Category.DOG,
      "assets/images/dogs/american_staffordshire_terrier.png",
      false,
      "43 cm - 48 cm",
      "17Kg - 20Kg",
      "De R\$ 1.500 a R\$ 5.000",
      "Varia de 12 a 15 anos",
      "O American Staffordshire Terrier pode ser facilmente confundido com um cão da raça Pit Bull. Isso acontece, principalmente, pelo formato da sua cabeça arredondada e semelhante a esse cachorro. No entanto, o temperamento deles é bem diferente. O cão American Staffordshire Terrier é muito dócil e brincalhão, onde ele está presente bom-humor não falta. Sua confiança com seus tutores é impressionante, demonstra ser muito apegado e amoroso com sua família sempre que possível!",
    ),
    Pet(
      "Basenji",
      "África do Sul",
      "condition",
      Category.DOG,
      "assets/images/dogs/basenji.png",
      false,
      "40 cm - 43 cm",
      "9Kg - 11Kg",
      "De R\$ 1.500 a R\$ 3.000",
      "Varia de 10 a 12 anos",
      "Quem vê o Basenji pela primeira vez, logo fica encantado com sua expressão viva e alegre. O peludinho de porte médio é considerado um dos mais antigos entre as raças de cães e, ao longo da história, desempenhou muito bem o papel de caçador, assim como companheiro fiel de seu tutor. Protetor e guardião, o animal também é brincalhão e super afetivo.",
    ),
    Pet(
      "Basset Hound",
      "França",
      "condition",
      Category.DOG,
      "assets/images/dogs/basset_hound.png",
      false,
      "33 cm - 38 cm",
      "22Kg - 29Kg",
      "De R\$ 1.500 a R\$ 4.000",
      "Varia de 12 a 15 anos",
      "Um dos motivos por trás dos tutores adotarem cãezinhos, é o fato de ver no pet um companheiro durante o dia a dia para ele e toda a família. Perfeito para esses casos, o cachorro Basset Hound se tornou popular justamente por toda a sua tranquilidade, companheirismo e bom humor. O Basset Hound é um cãozinho que não pode ser julgado pela aparência. Com orelhas longas e olhar cabisbaixo, quem vê pensa que ele é um animal triste. Porém, quem conhece, sabe que por trás de sua fisionomia, há um pet parceiro e amigável com todos.",
    ),
    Pet(
      "Beagle",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/beagle.png",
      true,
      "33 cm - 39 cm",
      "9Kg - 35Kg",
      "De R\$ 800 a R\$ 2.500",
      "Varia de 13 a 16 anos",
      "Experimente aparecer com qualquer alimento em um mesmo ambiente que um cachorro Beagle. Em instantes, ele estará em sua volta com uma carinha irresistível de pidão. Para conquistar a confiança e o amor desse cãozinho não é preciso muito, basta apenas oferecer algum lanchinho para ele. Porém, além de comilões, esses pets são sempre extrovertidos, brincalhões e agitados. Caso você seja um tutor de primeira viagem, prepare-se para mudar completamente sua rotina. Com esses pets, a diversão está garantida — mas a teimosia deles pode ser um problema.",
    ),
    Pet(
      "Beagle Harrier",
      "França",
      "condition",
      Category.DOG,
      "assets/images/dogs/beagle_harrier.png",
      false,
      "45 cm - 50 cm",
      "40Kg - 60Kg",
      "De R\$ 1.000 a R\$ 2.500",
      "Varia de 12 a 15 anos",
      "O Beagle Harrier é um cão desenvolvido para farejar raposas e lebres na França, país de origem dele. Esse instinto de caça permanece até hoje na raça, deixando o peludinho superenérgico e pronto para brincar a qualquer momento. Ele é facilmente confundido com o ancestral Beagle, principalmente pela aparência física. No entanto, o Beagle Harrier é uma raça muito rara, maior que o parente próximo citado e menor que outro antecessor, Harrier.",
    ),
    Pet(
      "Bearded Collie",
      "pais",
      "condition",
      Category.DOG,
      "assets/images/dogs/bearded_collie.png",
      false,
      "51 cm - 56 cm",
      "21Kg - 25Kg",
      "De R\$ 2.000 a R\$ 4.000",
      "Varia de 12 a 14 anos",
      "Quem adora cães bem peludos tem tudo para se encantar com a beleza e o carisma do Bearded Collie. O cãozinho é alerta, ativo e autoconfiante, por isso, é uma excelente opção de pet para tutores com certa experiência. Além desses traços, trata-se de um cachorro nada agressivo, com disposição e energia sem iguais.",
    ),
    Pet(
      "Bedlington Terrier",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/bedlington_terrier.png",
      false,
      "40 cm - 43 cm",
      "8Kg - 10Kg",
      "De R\$ 2.000 a R\$ 4.000",
      "Varia de 14 a 16 anos",
      "De longe, você pode pensar que está vendo uma ovelha. Mas, quando se aproximar, verá que está de frente com o Bedlington Terrier. Sua aparência parecida com um cordeirinho é inconfundível! Muito carinhoso, o Bedlington gosta de ser o centro das atenções na casa. Por isso, faz muitas graças e brincadeiras para que todos olhem para ele. Essa é uma raça extremamente companheira, pois adora ficar ao lado de quem ama e proteger seus amados da forma que pode!",
    ),
    Pet(
      "Bichon Frisé",
      "França",
      "condition",
      Category.DOG,
      "assets/images/dogs/bichon_frise.png",
      false,
      "24 cm - 30 cm",
      "7Kg - 12Kg",
      "De R\$ 1.000 a R\$ 2.000",
      "Varia de 12 a 15 anos",
      "De origens incertas, o bichon frisé é considerado um cachorro Francês, apesar de não se saber oficialmente se a raça foi criada lá. Ele é bastante parecido com o Poodle e acredita-se que o Maltês e o Barret estejam envolvidos geneticamente na criação dessa raça. Apesar de ser fisicamente muito parecido com o Poodle (e frequentemente até confundido com ele), as similaridades acabam por aí: o temperamento dos dois é um tanto quanto diferente. O Bichon é animado e se dá bem com crianças, ele gosta de carinho, brincadeiras e interação o tempo todo, mesmo que ela seja apenas ficando junto no sofá. Eles são tidos como uma das raças de cachorros mais dóceis, que recebem bem a todos, até mesmo aqueles que não conhecem.",
    ),
    Pet(
      "Bloodhound",
      "França",
      "condition",
      Category.DOG,
      "assets/images/dogs/bloodhound.png",
      false,
      "60 cm - 69 cm",
      "36Kg - 50Kg",
      "De R\$ 2.000 a R\$ 3.000",
      "Varia de 11 a 15 anos",
      "Antecessor de muitos Hounds que, assim como ele, seguem a presa pelo faro, o Bloodhound não tem concorrência no quesito seguir “pistas frias”, que foram deixadas há horas ou até mesmo dias. Também conhecido como Cão de Santo Humberto, a raça é completamente amigável e companheira. Criado no século VII, essa linhagem era usada para rastrear corças machucadas, o que explica seu nome em inglês, já que seguiam o rastro do sangue da presa. Logo após, suas habilidades foram utilizadas para seguir humanos. O grandalhão farejador costuma pesar entre 36 e 50 quilos, e sua altura pode chegar aos 69 centímetros.",
    ),
    Pet(
      "Bobtail",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/bobtail.png",
      false,
      "56 cm - 61 cm",
      "27Kg - 45Kg",
      "De R\$ 1.200 a R\$ 3.000",
      "Varia de 10 a 12 anos",
      "Bastante conhecido por seu senso de humor sem igual e aparições em filmes e programas de televisão, o Old English Sheepdog é um cão que encanta facilmente qualquer pessoa. A raça tem conquistado cada vez mais famílias com sua aparência fofinha e jeitinho dócil. Chamado também de Bobtail, esse peludo faz parte do grupo de cães pastores. Porém, é um pet que se adapta muito bem à vida comum, como um animal de companhia.",
    ),
    Pet(
      "Boiadeiro Australiano",
      "Austrália",
      "condition",
      Category.DOG,
      "assets/images/dogs/boiadeiro_australiano.png",
      false,
      "43 cm - 51 cm",
      "15Kg - 20Kg",
      "De R\$ 1.000 a R\$ 2.500",
      "Varia de 12 a 14 anos",
      "O Australian Cattle Dog é também conhecido no Brasil como Boiadeiro Australiano ou blue heeler e é uma raça muito peculiar. Forte, inteligente, resistente e extremamente leal aos seus humanos. Sua criação teve início no XIX na Austrália, como o próprio nome diz. Nesta época, criadores de gado em terrenos australianos dispunham de cães importados da Europa para desempenharem a função de boiadeiros (que pastoreiam o gado). No entanto, esses animais não eram adaptáveis às temperaturas e aos solos da Austrália, não desempenhando a função como esperado. Foi então que começou um processo de criação de uma raça específica para a região e que se adaptasse bem ao convívio com o rebanho. Diversas foram as tentativas a fim de se chegar a uma raça exemplar. Ela tinha que se dar bem com o ambiente e ser resistente o suficiente para lidar com diferentes situações, mas ao mesmo tempo deveria ser equilibrada a fim de não assustar os demais animais. Os primeiros cruzamentos se deram entre cães que vinham da Europa, especialmente da Inglaterra, com cachorros locais. A partir daí, os cruzamentos foram feitos a fim de adaptar os pontos que ainda eram negativos. Por exemplo: essa primeira “raça” era um tanto quanto agressiva com cavalos, por isso ela foi cruzada com um Dálmata, conhecido por se dar muito bem com os equinos. Collies e Bull Terriers também entraram nessa experiência genética. Podemos dizer que foi uma verdadeira jornada para chegar até o Boiadeiro Australiano que conhecemos hoje. Em 1980 ele foi reconhecido pelo American Kennel Club como uma raça oficial e vem ganhando espaço no Brasil, especialmente em regiões onde há grandes criações de gado.",
    ),
    Pet(
      "Boiadeiro Bernês",
      "Suíça",
      "condition",
      Category.DOG,
      "assets/images/dogs/boiadeiro_bernes.png",
      true,
      "58 cm - 70 cm",
      "30Kg - 55Kg",
      "De R\$ 2.500 a R\$ 5.000",
      "Varia de 7 a 10 anos",
      "É impossível resistir ao charme e beleza do Bernese! Conhecido como Boiadeiro de Berna, o cãozinho que parece estar sorrindo quando deixa a língua de fora, também é um ótimo companheiro e ama aproveitar longos momentos de lazer junto da sua família humana. O pet possui um passado como cão de guarda nos campos da Suíça, portanto, faz o possível para manter seu lar e tutores sempre protegidos. Ele é bem dócil, mas, quando se trata de defender as pessoas próximas o cachorro Bernese é bastante corajoso!",
    ),
    Pet(
      "Border Collie",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/border_collie.png",
      true,
      "45 cm - 55 cm",
      "13Kg - 20Kg",
      "De R\$ 1.500 a R\$ 2.500",
      "Varia de 12 a 15 anos",
      "Cães pastores fazem parte da história do planeta e ao longo de centenas de anos a criação desses cachorros tinha como objetivo principal desenvolver uma raça que exercesse esta função da forma mais eficiente possível. Existem registros datados do século de XVI que já evidenciam a existência de cães da raça Border Collie (que ainda não tinham esse nome). Eles eram perfeitos para o pastoreio nas regiões montanhosas da Grã-Bretanha se movimentando facilmente por mais de 50 quilômetros em um terreno irregular e até mesmo no frio durante um só dia. Além disso, esses cães se destacavam por não serem barulhentos e realizar o pastoreio sem latir ou mordiscar, apenas cercando agilmente o rebanho. O olhar do border collie também se destacava, uma vez que muitos donos de rebanho dizem até hoje que exemplares desta raça conseguem 'hipnotizar' os outros animais, mostrando o que desejam apenas os olhando de forma fixa e focada. Em 1925, o nome Border Collie foi oficialmente registrado, fazendo referência à sua origem entre as fronteiras Inglesas e escocesas. Já o reconhecimento pelo American Kennel Club só ocorreu mais recentemente, em 1995.",
    ),
    Pet(
      "Border Terrier",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/border_terrier.png",
      false,
      "20 cm - 40 cm",
      "5Kg - 7Kg",
      "De R\$ 1.500 a R\$ 3.000",
      "Varia de 12 a 15 anos",
      "Criado na fronteira entre a Inglaterra e a Escócia, há mais de 300 anos, o Border Terrier foi muito popular no condado de Northumberland (ING), sendo sua principal atividade na época correr ao lado das matilhas de hounds locais para espantar raposas dentro das tocas. Como consequência, a raça não ficou muito resistente, mas se entrosa mais rapidamente com outros cães do que muitos terriers. A linhagem é ativa e uma companhia alegre para aqueles que gostam de vida ao ar livre. Mesmo sendo pequeno, o Border tem muita energia, e só ficará feliz em um local no qual possa fazer muito exercício. Sua altura média é de 25 centímetros e seu peso pode variar entre cinco e sete quilos.",
    ),
    Pet(
      "Borzoi",
      "Rússia",
      "condition",
      Category.DOG,
      "assets/images/dogs/borzoi.png",
      false,
      "68 cm - 85 cm",
      "10Kg - 13Kg",
      "De R\$ 1.500 a R\$ 3.000",
      "Varia de 1 a 2 anos",
      "A beleza do Borzoi é inconfundível. A raça é conhecida por sua aparência elegante, com uma pelagem longa e sedosa. Além disso, o peludo é um velocista nato. Não à toa, ele conquista facilmente tutores que adoram velocidade e companheirismo. O melhor de tudo é que, além dessas qualidades, ele é um cão de personalidade descontraída. Ativo e inteligente, o cão Borzoi não dispensa a companhia do tutor e de outros integrantes da família.",
    ),
    Pet(
      "Boston Terrier",
      "Estados Unidos",
      "condition",
      Category.DOG,
      "assets/images/dogs/boston_terrier.png",
      false,
      "25 cm - 40 cm",
      "4Kg - 11Kg",
      "De R\$ 3.500 a R\$ 6.000",
      "Varia de 11 a 13 anos",
      "Criado nos Estados Unidos no século XIX, o boston terrier era utilizado para caçar ratos e torturar touros. Um tanto quanto parecido com o buldogue francês, este cão se diferencia por não ter tantas rugas no rosto e também por ser menos forte (pesando, no máximo, 11Kg). Atualmente, é considerado um cachorro para companhia, mas seu passado faz com que os pais humanos de bostons prestem atenção no comportamento de seus filhos de quatro patas - já que alguns exemplares podem se mostrar mais dominantes e desafiadores em relação a outros animais.",
    ),
    Pet(
      "Boxer",
      "Alemanha",
      "condition",
      Category.DOG,
      "assets/images/dogs/boxer.png",
      false,
      "53 cm - 63 cm",
      "25Kg - 30Kg",
      "De R\$ 1.500 a R\$ 3.500",
      "Varia de 8 a 12 anos",
      "Eles são grandes, brincalhões, agitados e muito inteligentes! Os Boxers podem assustar, logo de cara, por conta do seu tamanho e sua carinha um pouco enrugada, mas ao contrário do que muitos imaginam, eles são bastante carinhosos e amigos de toda a família. Originalmente, eles foram criados para desempenhar o papel de cão de guarda de médio porte, mas hoje se destacam muito como cães de companhia. O Boxer é um cão grande e musculoso que se destaca por sua docilidade e tolerância. Os Boxers gostam muito de brincar e na maioria das vezes, esquecem do seu tamanho se tornando desajeitados, simpáticos e super engraçados.",
    ),
    Pet(
      "Buldogue Francês",
      "França",
      "condition",
      Category.DOG,
      "assets/images/dogs/buldogue_frances.png",
      true,
      "29 cm - 35 cm",
      "8Kg - 14Kg",
      "De R\$ 2.500 a R\$ 8.000",
      "Varia de 9 a 12 anos",
      "Também conhecido como “Frenchie”, acredita-se que o buldogue francês teve sua origem em três países: Inglaterra, França e Estados Unidos. Os criadores da raça defendem que a Inglaterra é responsável pela origem no antigo Buldogue. A França ajudou a desvincular os Buldogues Franceses dos Buldogues ingleses e os EUA foram os responsáveis por trazerem as orelhinhas pra cima, característica muito conhecida desses pets.",
    ),
    Pet(
      "Buldogue Inglês",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/buldogue_ingles.png",
      false,
      "30 cm - 40 cm",
      "20Kg - 25Kg",
      "De R\$ 2.500 a R\$ 8.000",
      "Varia de 8 a 12 anos",
      "A origem dos Buldogues Ingleses sempre gerou polêmicas. A raça, a princípio, era usada no século XIII em um esporte chamado bull-baiting (luta com touros), no qual o objetivo era que os cães provocassem os touros com a intenção de entreter os que assistiam o evento. A “briga” entre cachorro e touro também fazia com que a carne bovina ficasse mais macia para quando fosse abatido. Depois de muitos anos, essa prática finalmente tornou-se ilegal e os buldogues ingleses quase foram extintos. O que os salvou foi ter tantos admiradores de sua aparência diferenciada, que continuaram a cuidar deles mesmo após o final dessa “luta”.",
    ),
    Pet(
      "Bull Terrier",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/bull_terrier.png",
      false,
      "53 cm - 56 cm",
      "20Kg - 40Kg",
      "De R\$ 3.500 a R\$ 6.000",
      "Varia de 10 a 15 anos",
      "O bull terrier é um cachorro diferente de todos os outros. Com seu focinho alongado, ele não possui uma “separação” em seu crânio como os outros, o que lhe dá uma aparência única e super exótica, no estilo 'cabeça ova'. Criado no século XIX no Reino Unido, esse cão foi selecionado para ser destemido a ponto de enfrentar touros e outros animais de grande porte. Também chamada “english bull terrier”, a raça é conhecida em diversas partes do mundo e hoje quase não é mais vista realizando sua “função” original.",
    ),
    Pet(
      "Bulmastife",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/bulmastife.png",
      false,
      "61 cm - 68 cm",
      "41Kg - 59Kg",
      "De R\$ 2.000 a R\$ 3.500",
      "Varia de 8 a 12 anos",
      "Se você é apaixonado por cães de grande porte, com certeza, vai adorar conhecer o Bullmastiff. A raça é famosa não só pelo tamanho, mas por seu temperamento calmo, afetuoso e companheiro com a família adotiva. Ainda assim, trata-se de um excelente cão de guarda, com instinto protetor e alerta.",
    ),
    Pet(
      "Cairn Terrier",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/cairn_terrier.png",
      false,
      "28 cm - 31 cm",
      "6Kg - 7Kg",
      "De R\$ 1.500 a R\$ 3.000",
      "Varia de 12 a 15 anos",
      "A própria denominação da raça (Terrier) dá uma boa pista sobre os instintos desse animal: gosta de cavar, latir e perseguir. Outros adjetivos podem ser aplicados a esse cão de origem escocesa facilmente como alegre, inteligente e que ama receber atenção da sua família, principalmente em forma de brincadeiras. São cães ideais para casa ou apartamentos pequenos, pois embora sejam muito ativos, não precisam de muito espaço para gastar suas energias. Corajosos, adoram caçar, principalmente insetos e roedores, e estão ligados em tudo ao seu redor. É ele quem vai te avisar sobre a presença de qualquer visitante.",
    ),
    Pet(
      "Cane Corso",
      "Itália",
      "condition",
      Category.DOG,
      "assets/images/dogs/cane_corso.png",
      false,
      "60 cm - 68 cm",
      "40Kg - 50Kg",
      "De R\$ 1.500 a R\$ 4.000",
      "Varia de 10 a 12 anos",
      "Grande, imponente e bastante forte, o cane corso (também conhecido como mastim italiano) costuma ser usado como cão de guarda. Seus parentes mais próximos eram caçadores de javali e cães de combate, além de guardas de regiões rurais e gado, por isso sua aparência imponente que promete colocar medo em muita gente. A raça quase entrou em extinção na década de 1970, mas alguns criadores de cane corso conseguiram reverter essa situação. Hoje, este cachorro é mais popular em outros países do que na própria Itália, sendo comum para guarda de grandes residências em diferentes países.",
    ),
    Pet(
      "Cão de Água Português",
      "Portugal",
      "condition",
      Category.DOG,
      "assets/images/dogs/cao_de_agua_portugues.png",
      false,
      "43 cm - 70 cm",
      "16Kg - 25Kg",
      "De R\$ 1.500 a R\$ 3.000",
      "Varia de 10 a 14 anos",
      "O cão d’água português ficou bem popular nos últimos anos por ser uma das raças prediletas do ex-presidente dos Estados Unidos. Barack Obama frequentemente aparecia com seus exemplares da raça, fazendo com que este simpático cão ficasse mais conhecido fora da Europa. Às vezes parecido com o poodle gigante (especialmente quando todo preto), o cão d’água português, como o próprio nome sugere, é um excelente nadador e adora qualquer tipo de atividade que envolva água. Isso, obviamente, pode ser um problema quando chove, já que esses cãezinhos gostam muito de brincar na chuva.",
    ),
    Pet(
      "Cão de Crista Chinês",
      "China",
      "condition",
      Category.DOG,
      "assets/images/dogs/cao_de_crista_chines.png",
      false,
      "23 cm - 33 cm",
      "4Kg - 5Kg",
      "De R\$ 2.000 a R\$ 4.000",
      "Varia de 10 a 14 anos",
      "Uma coisa é certa: ninguém fica indiferente ao ver um cãozinho dessa raça em sua versão (quase) sem pelos! Exótico por natureza, o Cão de Crista Chinês pode ser encontrado na versão peluda, mas é na versão mais “tosada” que ele faz mais sucesso. Bastante alegre, elegante e inteligente, é um excelente companheiro e sempre vai procurar se aconchegar no seu colo em busca de um carinho. Em casa ou nos passeios, adora pular, escalar e cavar, por isso é bom manter o ambiente protegido e usar guias quando for sair - olhos fixos nele! O baixinho de aproximadamente 30 cm se move muito rápido e é um tanto teimoso, pode ser uma tarefa dura recapturá-lo em uma tentativa de fuga.",
    ),
    Pet(
      "Cavalier King Charles Spaniel",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/cavalier_king_charles_spaniel.png",
      false,
      "25 cm - 34 cm",
      "5Kg - 8Kg",
      "De R\$ 3.500 a R\$ 6.500",
      "Varia de 9 a 15 anos",
      "Carinhoso com todos e muito apegado aos seus pais humanos, o cavalier king charles spaniel não tem esse nome a toa: a raça era uma das favoritas do Rei Charles, fazendo com que sempre fosse símbolo de status e boa companhia. Parente direto do King Charles Spaniel (com o qual muito se parece fisicamente), podemos dizer que esta é uma versão mais moderna desses cães que estão conosco desde o século XVII. Reconhecido oficialmente no ano de 1945, o cavalier foi criado na Grã-Bretanha e em pouco tempo ganhou o mundo com seu jeito meigo e calmo. Podemos dizer que este é um dos cachorros mais companheiros e tranquilos que existe na atualidade, sempre se mostrando muito amistoso mesmo com aqueles que não conhece, incluindo outros animais.",
    ),
    Pet(
      "Chesapeake Bay Retriever",
      "Estados Unidos",
      "condition",
      Category.DOG,
      "assets/images/dogs/chesapeake_bay_retriever.png",
      false,
      "53 cm - 66 cm",
      "25Kg - 37Kg",
      "De R\$ 2.500 a R\$ 5.000",
      "Varia de 10 a 12 anos",
      "Há muitos motivos pelos quais nos apaixonamos por cachorros. Alguns cães impressionam pela força e imponência, enquanto outros se destacam pela elegância e inteligência. O Chesapeake Bay Retriever se diferencia por ser um excelente nadador, por exemplo, mas também é uma ótima companhia! Com certeza, essa é uma das raças de cachorro mais aventureiras que há. Afinal, ela foi criada para a caça de aves aquáticas, adora correr pela natureza e se molhar.",
    ),
    Pet(
      "Chihuahua",
      "México",
      "condition",
      Category.DOG,
      "assets/images/dogs/chihuahua.png",
      false,
      "16 cm - 20 cm",
      "1Kg - 3Kg",
      "De R\$ 1.500 a R\$ 8.000",
      "Varia de 12 a 20 anos",
      "Considerado um dos menores cães do mundo, o chihuahua só não tem tamanho: seu jeito atrevido e brincalhão faz com que os pais humanos desta raça sejam realmente apaixonados por seus pequenos filhotes. Se engana quem acha que, por seu pequeno porte, ele é do tipo medroso. Ao contrário disso, o cachorro chihuahua tende a ser destemido e cheio de coragem, se mostrando valente até para pets que têm muito mais tamanho do que ele. Criado no México no século XIX como cão de companhia, seu nome é uma homenagem ao estado em que surgiram os seus primeiros exemplares.",
    ),
    Pet(
      "Chow Chow",
      "China",
      "condition",
      Category.DOG,
      "assets/images/dogs/chow_chow.png",
      false,
      "45 cm - 56 cm",
      "20Kg - 25Kg",
      "De R\$ 2.000 a R\$ 4.000",
      "Varia de 12 a 15 anos",
      "Parecido com um urso, o chow chow não tem como passar por alguém sem chamar a atenção. Extremamente peludo e super imponente, este cachorro de origem chinesa foi criado nos anos 100 para ser cão de guarda e de tração. Fortes e bem dominantes, eles se destacavam como nenhum outro cachorro da região nessas funções.",
    ),
    Pet(
      "Cocker Spaniel Americano",
      "Estados Unidos",
      "condition",
      Category.DOG,
      "assets/images/dogs/cocker_spaniel_americano.png",
      false,
      "34 cm - 39 cm",
      "12Kg - 14Kg",
      "De R\$ 2.000 a R\$ 5.000",
      "Varia de 12 a 15 anos",
      "Orelhas compridas, pelo longo, mas com um focinho achatado. O cocker spaniel americano é bastante parecido com o cocker spaniel inglês, mas a conformação de sua cabeça e de seu focinho fazem com que sejam duas raças distintas. Criado no século XIX nos Estados Unidos, esse cachorro caçava codornas e outras aves de pequeno porte. Hoje, porém, é popular como um cão de companhia.",
    ),
    Pet(
      "Cocker Spaniel Inglês",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/cocker_spaniel_ingles.png",
      false,
      "38 cm - 41 cm",
      "12Kg - 14Kg",
      "De R\$ 1.200 a R\$ 4.500",
      "Varia de 12 a 14 anos",
      "Inicialmente, o Cocker spaniel Inglês e Cocker spaniel Americano eram considerados uma só raça. Apenas em 1946 elas foram separadas, quando suas diferenças físicas e de personalidade foram final,ente reconhecidas. Somente na América Latina o Cocker Spaniel Inglês é o mais popular. A cadela do filme A Dama e o Vagabundo, por exemplo, é um cocker americano, embora muitos de nós façamos uma associação direta ao inglês (bem mais familiar para nós).",
    ),
    Pet(
      "Collie",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/collie.png",
      false,
      "51 cm - 61 cm",
      "18Kg - 30Kg",
      "De R\$ 1.500 a R\$ 3.000",
      "Varia de 10 a 14 anos",
      "Famoso pelo papel de “Lassie”, o collie é um dos cães mais populares do mundo todo. Este pastor de ovelhas criado na Grã-Bretanha é leal e muito cooperativo com seus pais humanos, se destacando como uma das raças mais obedientes de todas. Collies costumam ser bem tolerantes e se dão bem com vários animais, se adaptando tanto ao ambiente urbano quanto em fazendas com muita facilidade. A raça gosta muito de esportes e atividades que podem fazer em conjunto com sua família. Seu pelo longo é chamativo e dá um toque especial a esse cachorro tão amoroso.",
    ),
    Pet(
      "Coton de Tuléar",
      "Madagáscar",
      "condition",
      Category.DOG,
      "assets/images/dogs/coton_de_tulear.png",
      false,
      "22 cm - 32 cm",
      "3Kg - 6Kg",
      "De R\$ 1.500 a R\$ 3.500",
      "Varia de 13 a 16 anos",
      "Imagine uma bolinha branca, parecida com algodão, correndo pela casa. Esse é o Coton de Tulear, um cãozinho que adora brincadeiras. E esses momentos serão ainda mais agradáveis se os tutores estiverem junto, pois esse cachorro é muito fiel aos seus familiares e quer sempre demonstrar carinho. O nome do cachorro Coton Tulear vem da junção de “cotón”, que significa algodão em francês, e Tulear, uma região de Madagascar. Esse país da África foi o local em que o cãozinho surgiu e permaneceu exclusivamente por alguns anos. Em todo esse tempo, demonstrou sua fidelidade aos seus tutores, que é a sua maior característica.",
    ),
    Pet(
      "Dachshund",
      "Alemanha",
      "condition",
      Category.DOG,
      "assets/images/dogs/dachshund.png",
      false,
      "30 cm - 35 cm",
      "3Kg - 9Kg",
      "De R\$ 1.000 a R\$ 2.500",
      "Varia de 12 a 15 anos",
      "Inicialmente um cão de caça — que dá origem ao seu nome — o cachorro Dachshund atualmente é um excelente parceiro para companhia. Corajosos, os salsichas, como também são conhecidos, são curiosos e podem passar horas entretidos se começarem a farejar algo interessante, fazendo jus a sua origem. Além de diversos apelidos, para tutores que estão interessados em adotar um cãozinho desse na família, é importante saber quais das três opções de tamanho (Kaninchen, Miniatura e Padrão) ou pelagem (pelo curto, pelo duro e pelo longo) há maior compatibilidade com a rotina familiar.",
    ),
    Pet(
      "Dálmata",
      "Croácia",
      "condition",
      Category.DOG,
      "assets/images/dogs/dalmata.png",
      false,
      "54 cm - 61 cm",
      "24Kg - 32Kg",
      "De R\$ 1.200 a R\$ 2.000",
      "Varia de 10 a 13 anos",
      "O Dálmata é uma das raças mais reconhecidas no mundo todo devido à sua aparência física tão característica. E também, claro, em 1961 o lançamento do clássico da Disney “101 Dálmatas” fez com que esses cãezinhos ganhassem ainda mais notoriedade. Apesar de todo mundo conhecer a história do filme, a origem da raça é incerta. O nome provém da região da Dalmácia, na Croácia, onde existem vestígios da raça. No entanto outros indícios mais antigos de que a raça já existia foram encontrados. Por exemplo, no Egito encontraram pinturas em tumbas que se assemelhavam muito às características do Dálmata. Além disso, desenhos dentro de uma capela na Itália datadas de 1360 retratavam cães manchados, parecidos com os Dálmatas que conhecemos hoje. Em 1888 a raça foi registrada oficialmente pelo American Kennel Club.",
    ),
    Pet(
      "Dandie Dinmont Terrier",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/dandie_dinmont_terrier.png",
      false,
      "25 cm - 30 cm",
      "6Kg - 11Kg",
      "De R\$ 1.500 a R\$ 3.500",
      "Varia de 12 a 15 anos",
      "Este pequenino de olhos grandes e escuros é de uma raça rara e não nega que é um Terrier, já que ama os momentos de caça. Independente e afetuoso, o Dandie Dinmont Terrier é indicado para casas com quintais ou com um pouco mais de espaço para que o peludinho possa deixar a sua imensa curiosidade fluir. Os cães dessa raça também são excelentes vigilantes e têm uma boa dose de coragem.",
    ),
    Pet(
      "Dobermann",
      "Alemanha",
      "condition",
      Category.DOG,
      "assets/images/dogs/dobermann.png",
      true,
      "63 cm - 72 cm",
      "32Kg - 45Kg",
      "De R\$ 1.200 a R\$ 4.500",
      "Varia de 10 a 13 anos",
      "Criado na Alemanha no século XIX, o doberman era bastante utilizado como cão de guarda. Imponente, ele tem uma aparência elegante e costuma ser um cachorro esbelto e musculoso. Curiosamente, o doberman é resultado de uma grande mistura de raças como o pastor alemão, rottweiler, pinscher e alguns terriers. No Brasil, o corte de suas orelhas e rabo não são permitidos, mas isso ainda é realizado em outros países.",
    ),
    Pet(
      "Dogo Argentino",
      "Argentina",
      "condition",
      Category.DOG,
      "assets/images/dogs/dogo_argentino.png",
      false,
      "60 cm - 68 cm",
      "40Kg - 50Kg",
      "De R\$ 1.200 a R\$ 4.000",
      "Varia de 10 a 12 anos",
      "Quem vê o Dogo Argentino pela primeira vez, talvez até se engane com sua fisionomia séria. Mas, na verdade, a aparência rústica e atlética contrasta com uma personalidade alegre e carismática. Não é à toa que o apego entre ele e seu tutor seja sempre tão forte. Acompanhe o guia que preparamos e saiba tudo sobre essa raça tão popular na terra dos nossos hermanos. Assim, você já fica apto para receber um filhote desse cachorro como novo integrante da família!",
    ),
    Pet(
      "Dogue Alemão",
      "Alemanha",
      "condition",
      Category.DOG,
      "assets/images/dogs/dogue_alemao.png",
      false,
      "72 cm - 80 cm",
      "50Kg - 70Kg",
      "De R\$ 2.000 a R\$ 5.000",
      "Varia de 7 a 10 anos",
      "Quem vê o Dogue Alemão pela primeira vez fica impressionado com o porte nada comum. Mas o que ele tem altura, tem de companheirismo. Trata-se de um cão que tem muito bom humor e se apega facilmente à família. O apreço pela presença constante do tutor é bastante perceptível. Portanto, quem pensa em adotar esse peludo, precisa dedicar tempo, pois ele sempre vai querer muita atenção. Além de dócil e de fácil trato, é um animal corajoso e autoconfiante. Não é à toa que seja tão popular!",
    ),
    Pet(
      "Fila Brasileiro",
      "Brasil",
      "condition",
      Category.DOG,
      "assets/images/dogs/fila_brasileiro.png",
      false,
      "60 cm - 75 cm",
      "40Kg - 50Kg",
      "De R\$ 1.200 a R\$ 3.000",
      "Varia de 10 a 12 anos",
      "Imagina carregar consigo a honra de ter sido a primeira raça de cachorro brasileira reconhecida internacionalmente. Esse é o mérito do Fila Brasileiro, um pet robusto e extremamente fiel aos seus tutores, que te surpreende desde o primeiro dia juntos.",
    ),
    Pet(
      "Fox Terrier (Pelo Duro e Pelo Liso)",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/fox_terrier_pelo_duro_e_pelo_liso.png",
      false,
      "37 cm - 39 cm",
      "7Kg - 8Kg",
      "De R\$ 1.200 a R\$ 4.500",
      "Varia de 10 a 15 anos",
      "O Fox Terrier possui todas as qualidades de um bom terrier: são animados, ativos, alertas e fofos! Originários da Grã Bretanha, esses cãezinhos surgiram a partir do cruzamento de diversas raças como Teckels, Beagles e outros Terriers. O mais antigo registro dos primeiros animais dessa raça data de 1790 e é um quadro pertencente ao coronel Thomas Thornton que mostrava seu cachorro Pitch, muito semelhante ao Fox Terrier que conhecemos hoje. A raça possui dois padrões distintos: o Fox Terrier de pelo duro e o de pelo liso. Alguns criadores chegaram a cruzar os dois padrões para criar uma variação mais uniforme, mas o processo não continuou. O nome Fox Terrier vem da excelente performance que esses animais desempenhavam em caçar raposas (Fox = raposa). Em 1885 o primeiro Fox Terrier foi registrado pelo American Kennel Club. Porém em 1985 o AKC reconheceu formalmente o Fox Terrier de pelo duro e o de pelo liso como raças distintas.",
    ),
    Pet(
      "Foxhound Inglês",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/foxhound_ingles.png",
      false,
      "58 cm - 68 cm",
      "30Kg - 35Kg",
      "De R\$ 1.500 a R\$ 2.500",
      "Varia de 10 a 13 anos",
      "Originalmente criados para caçar raposas, o Foxhound Inglês é bastante confundido com o seu primo homônimo americano. Um olhar mais atento, porém, perceberá que o cão inglês tende a ser mais robustos que o americano. Geralmente o cão da Terra da Rainha tem entre 58 e 68cm, pesa até 35kg, possui cauda longa e pode ser encontrado nas cores: preto, branco e castanho.",
    ),
    Pet(
      "Galgo Escocês",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/galgo_escoces.png",
      false,
      "71 cm - 80 cm",
      "36Kg - 45Kg",
      "De R\$ 3.500 a R\$ 5.500",
      "Varia de 8 a 11 anos",
      "O galgo escocês, mais conhecido mundialmente como deerhound, é um dos cachorros mais altos do mundo. Medindo cerca de 80cm, ele pode pesar aproximadamente 45Kg, o que faz dele um pet um tanto quanto elegante. Seu pelo arame é bem diferente, assim como o formato de sua cabeça. característica dos cães de corrida. Criado na Grã-Bretanha no século IX, o deerhound era comumente utilizado para caçar veados com muita rapidez e destreza. No Brasil, é uma raça rara, mas hoje é frequentemente visto como cão de companhia em outros países.",
    ),
    Pet(
      "Galgo Irlandês",
      "Irlanda",
      "condition",
      Category.DOG,
      "assets/images/dogs/galgo_irlandes.png",
      false,
      "71 cm - 86 cm",
      "40Kg - 55Kg",
      "De R\$ 8.000 a R\$ 10.000",
      "Varia de 6 a 8 anos",
      "Imagine um cão tão grande a ponto de ser do tamanho de uma pessoa adulta. Imaginou? Esse é o Lébrel Irlandês. Sua altura é a característica mais marcante para quem o vê pela primeira vez. Mas todo esse tamanho não o transforma em um cachorro bravo, pelo contrário. Em casa, o cão Lébrel Irlandês é extremamente dócil e companheiro de seus tutores. Sem deixar as características de caça de lado, ele está sempre alerta para qualquer situação de defesa.",
    ),
    Pet(
      "Golden Retriever",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/golden_retriever.png",
      true,
      "60 cm - 68 cm",
      "35Kg - 40Kg",
      "De R\$ 2.000 a R\$ 2.500",
      "Varia de 7 a 9 anos",
      "De origem britânica, conhecido por ser muito dócil e companheiro, o Golden Retriever é considerado por muitos o “cão dos sonhos”. Bastante inteligente, pronto para aprender truques e muitas vezes usados como cães-guia, o Golden é um cachorro ativo e que gosta de ajudar e agradar a todos (inclusive aqueles que não conhece tão bem). Adora truques e precisa de muita atenção e de tempo disponível para gastar sua energia. Ele também é um ótimo nadador e o favorito de várias famílias, algo que fez com que a sua popularidade ficasse bastante alta nas últimas décadas aqui no Brasil e no mundo.",
    ),
    Pet(
      "Grande Boiadeiro Suiço",
      "Suíça",
      "condition",
      Category.DOG,
      "assets/images/dogs/grande_boiadeiro_suico.png",
      false,
      "53 cm - 63 cm",
      "25Kg - 30Kg",
      "De R\$ 1.500 a R\$ 3.500",
      "Varia de 8 a 12 anos",
      "Obediente e confiável, o Grande Boadeiro Suíço é facil de ser adestrado. Por isso, a ele são destinados múltiplas tarefas; vigia bois, puxa pesadas cargas ou guarda fazendas e casas. Seu físico impressionante e sua voz grave são suficientes para afastar intrusos. É melhor educá-los muito cedo e com firmeza, mas sem violência, do contrário será difícil dominá-lo na idade adulta. Alerta, amigável e fiel. bem como muito protetor com  crianças, o Grande Boiadeiro Suíço é também um cão de companhia muito apreciado.",
    ),
    Pet(
      "Greyhound",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/greyhound.png",
      false,
      "68 cm - 76 cm",
      "30Kg - 35Kg",
      "De R\$ 1.200 a R\$ 2.500",
      "Varia de 10 a 13 anos",
      "Conhecido por ser muito rápido, o Greyhound é um cão muito gentil e amigável. É o mais veloz de todos os Lebréus e muito resistente também. Essa raça é muito apegada a seu tutor, além de se dar muito bem com as crianças. Apesar de sua fama vir das corridas, o Galgo Inglês na verdade, ama ficar deitando e aproveitando carinhos. É muito conhecido por sua tranquilidade e por ser um animal que ama o ar livre. Além de ser também muito obediente e inteligente, podendo ser treinado com facilidade. A raça Greyhound é ideal para quem busca um bichinho companheiro, que estará a seu lado em todos os momentos.",
    ),
    Pet(
      "Grifo da Bélgica",
      "Bélgica",
      "condition",
      Category.DOG,
      "assets/images/dogs/grifo_da_belgica.png",
      false,
      "28 cm - 30 cm",
      "4Kg - 6Kg",
      "De R\$ 1.800 a R\$ 2.500",
      "Varia de 12 a 15 anos",
      "Com muita inteligência e curiosidade, o Griffon de Bruxelas é um cão que está sempre em alerta. Mesmo não sendo um cachorro de grande porte, sabe impor seu respeito e adora cuidar da casa e proteger seus tutores. De origem belga, o cãozinho também é conhecido como Griffon Belga, Griffon de Bruxelas, Pequeno Brabação e Grifo da Bélgica. Esse pet é um excelente cão para tutores que vivem em espaços pequenos, como apartamentos, já que são menores e se adaptam melhor aos ambientes limitados.",
    ),
    Pet(
      "Husky Siberiano",
      "Rússia",
      "condition",
      Category.DOG,
      "assets/images/dogs/husky_siberiano.png",
      false,
      "51 cm - 60 cm",
      "15Kg - 28Kg",
      "De R\$ 800 a R\$ 1.500",
      "Varia de 12 a 15 anos",
      "Seu nome não deixa dúvidas: o Husky siberiano surgiu na Sibéria há cerca de dois mil anos. A criação e dispersão da raça é atribuída a uma tribo chamada Chukchi, que utilizava os cachorros para puxarem os trenós. As características físicas do Husky eram ideais para aguentar as longas distâncias, puxar objetos e também suportar o frio da Sibéria. Em 1909 William Goosak, um comerciante de peles, levou os Huskys até o Alasca para participarem da Grande Corrida do Alasca, um percurso de 657 km. Os Huskys impressionaram pelo alto desempenho e começaram a ganhar notoriedade. Mas foi em 1925 que essa raça ganhou reconhecimento mundial. Uma pequena cidade do Alasca chamada “Nome” foi assolada por uma epidemia de difteria, foram grupos de cães, principalmente de Huskys, que levaram soro e medicamentos para essa aldeia enfrentando um inverno rigoroso e acabaram por salvar a população. O episódio ficou conhecido como “Corrida do Soro de Nome” e o Husky Siberiano alcançou seu lugar de destaque. Em 1930 a raça foi reconhecida oficialmente pelo American Kennel Club.",
    ),
    Pet(
      "Jack Russell Terrier",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/jack_russell_terrier.png",
      false,
      "23 cm - 30 cm",
      "5Kg - 6Kg",
      "De R\$ 2.000 a R\$ 4.000",
      "Varia de 10 a 15 anos",
      "O Jack Russell Terrier surgiu da mistura entre o Fox Terrier e o White Terrier Inglês (raça que não existe mais) na Inglaterra, no século XIX. Um cão de pequeno porte, mas com uma personalidade super forte, que costuma ser descrito como um cão de “personalidade maior que o seu tamanho”. Além disso, o Jack Russell é muito companheiro e sociável. São cachorros muito corajosos e determinados e exigem muita atenção e energia dos seus pais humanos. Os cruzamentos iniciais para criar o Jack Russell Terrier tinham como objetivo criar o melhor cão caçador de raposas possível.",
    ),
    Pet(
      "King Charles",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/king_charles.png",
      false,
      "25 cm - 30 cm",
      "3Kg - 6Kg",
      "De R\$ 3.500 a R\$ 6.500",
      "Varia de 10 a 12 anos",
      "O Cavalier King Charles Spaniel é um cãozinho extremamente fofo e grudento. Sim, ele é muito fiel e apegado ao seu tutor! Adora ter toda a atenção do mundo dedicada a ele, incluindo ficar horas e horas deitado no colo. Mas esse é apenas um aperitivo de tudo que você irá descobrir sobre essa querida raça.",
    ),
    Pet(
      "Komondor",
      "Hungria",
      "condition",
      Category.DOG,
      "assets/images/dogs/komondor.png",
      false,
      "66 cm - 76 cm",
      "36Kg - 61Kg",
      "De R\$ 2.000 a R\$ 3.500",
      "Varia de 10 a 12 anos",
      "Independente, inteligente e altamente protetor. Essas são as principais características do Komondor, um cão que é considerado por muitos, o dono do visual mais exótico do mundo canino. Por baixo de todo aquele pelo existe um animal de grande personalidade. Esses grandalhões agem de acordo com a própria percepção e quase sempre acertam devido à surpreendente capacidade de julgar se uma pessoa tem más intenções. Originário da Hungria, seu nome significa “pertencente aos cumans”, um povo que invadiu seu país durante o século XVIII, o que pode explicar suas origens. Sua principal função, histórica e atualmente, já que ainda é usado, é ser guarda de rebanhos, vigiando ovelhas e gado bovino e os protegendo de ladrões ou predadores de quatro patas. Sua altura está na faixa entre 66 e 76 centímetros, enquanto seu peso varia entre 36 e 61 quilos.",
    ),
    Pet(
      "Labradoodle",
      "Austrália",
      "condition",
      Category.DOG,
      "assets/images/dogs/labradoodle.png",
      false,
      "53 cm - 60 cm",
      "22Kg - 29Kg",
      "De R\$ 1.500 a R\$ 4.000",
      "Varia de 10 a 15 anos",
      "O Labradoodle é um cão inteligente que pode ser o animal de estimação ideal se devidamente treinado. Ele é amigável, aceita e trata a todos como seus melhores amigos. Ele é dedicado a sua família e goza a vida como um companheiro energético. Ele pode ser gentil e também pode ser alegre, mostrando sua felicidade através de saltos exuberantes. Ele também tende a ser descontraído, uma vez que o Labradoodle foi criado para não ser agressivo. Como é o caso com qualquer raça, alguns criados irresponsáveis podem dar origem a cães não tão amigáveis, mas um Labradoodle bem educado com um temperamento característico é uma verdadeira alegria.",
    ),
    Pet(
      "Labrador Retriever",
      "Canadá",
      "condition",
      Category.DOG,
      "assets/images/dogs/labrador_retriever.png",
      false,
      "54 cm - 57 cm",
      "23Kg - 30Kg",
      "De R\$ 1.200 a R\$ 3.000",
      "Varia de 10 a 13 anos",
      "Criado no século XIX no Canadá, o retriever do labrador (ou labrador retriever) é um dos cachorros mais populares do mundo. Sempre muito amável, amistoso e obediente, ele se destaca hoje em dia como um excelente cachorro da família, mas décadas atrás, era bastante utilizado como “cão de pesca”.",
    ),
    Pet(
      "Lakeland Terrier",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/lakeland_terrier.png",
      false,
      "35 cm - 37 cm",
      "6Kg - 8Kg",
      "De R\$ 1.500 a R\$ 3.500",
      "Varia de 12 a 15 anos",
      "O Lakeland Terrier é um cachorro afetuoso, com bastante disposição e exímio caçador (como a maioria dos Terriers). O peludinho também é autoconfiante, inteligente e divertido e adora estar na companhia da família, mas pode ter certa dificuldade em compartilhar, pois é um tanto possessivo. Mostre que você é digno de seu amor e carinho e espere por um cão cheio de qualidades e parceiro fiel.",
    ),
    Pet(
      "Leonberger",
      "Alemanha",
      "condition",
      Category.DOG,
      "assets/images/dogs/leonberger.png",
      false,
      "65 cm - 80 cm",
      "45Kg - 77Kg",
      "De R\$ 1.500 a R\$ 4.500",
      "Varia de 6 a 9 anos",
      "O grandalhão alemão de cara escura é uma mistura das raças Terra Nova, São Bernardo e Cão dos Pirineus. Forte e elegante, o Leonberger pode se sair bem em diversas atividades, como resgates, prova aquáticas e até de agilidade. Na vida familiar precisa receber uma boa socialização desde muito jovem para aprender boas maneiras, já que deixá-lo sempre agir por conta própria pode ter um preço a se pagar: ter dentro de casa um pet bastante travesso e capaz de usar qualquer objeto disponível para brincar de roer e destruir. Bem treinado, pode viver muito bem ao lado da família humana e será um companheiro leal e protetor.",
    ),
    Pet(
      "Lhasa Apso",
      "China",
      "condition",
      Category.DOG,
      "assets/images/dogs/lhasa_apso.png",
      false,
      "24 cm - 25 cm",
      "4Kg - 7Kg",
      "De R\$ 800 a R\$ 2.000",
      "Varia de 12 a 15 anos",
      "Apesar de parecer um cachorrinho frágil e mimado, o Lhasa Apso é um tanto quanto genioso! Criado no Tibete, esses cãezinhos eram considerados sagrados e só quem os possuíam eram os monges tibetanos ou os nobres. A raça carrega uma história muito mística, já que acreditava-se que quando o dono de um Lhasa Apso morria, sua alma reencarnava em um outro cachorro da mesma raça. Eram considerados animais que traziam sorte e prosperidade e só podiam deixar o território se fossem dados como presente. Em 1933 um casal da raça foi dado pelo 13º Dalai Lama para um pesquisador chamado Suydam Cutting que, então, iniciou a criação da raça nos Estados Unidos que só foi reconhecida pelo Kennel Club em 1935.",
    ),
    Pet(
      "Lulu da Pomerânia",
      "Polónia",
      "condition",
      Category.DOG,
      "assets/images/dogs/lulu_da_pomerania.png",
      true,
      "18 cm - 22 cm",
      "3Kg - 4Kg",
      "De R\$ 3.500 a R\$ 7.000",
      "Varia de 15 a 16 anos",
      "Rei dos apelidinhos fofinhos, o cachorro Lulu da Pomerânia encanta com sua pelagem única e uma alegria sem fim. Excelente cão de companhia, por adorar estar por perto de seu tutor, esse cachorro também é ótimo guardião e late ao notar qualquer movimentação diferente. Um dos animais favoritos para quem mora em apartamento, esse pet lida bem com a ausência do seu tutor, mas, ao perceber sua chegada, faz de tudo para ganhar a sua atenção e passa horas brincando e correndo pelo ambiente.",
    ),
    Pet(
      "Malamute do Alasca",
      "Alasca",
      "condition",
      Category.DOG,
      "assets/images/dogs/malamute_do_alasca.png",
      false,
      "58 cm - 65 cm",
      "35Kg - 39Kg",
      "De R\$ 2.500 a R\$ 4.000",
      "Varia de 12 a 15 anos",
      "Muito confundido com o husky siberiano, o malamute do Alasca é um enorme cão de neve, que desde o ano 3000a.c. era utilizado para puxar trenós e pequenos carros com objetos, servindo como cachorro de tração. Criado nos Estados Unidos, este cachorro é forte e poderoso, podendo chegar aos 60Kg sem estar acima do peso. Por ser um cão de trabalho, o malamute costuma ser bastante focado e se dá bem em matilha, especialmente com pets de sua raça e que também trabalham como ele. Sua convivência com animais de outras espécies e crianças deve ser incentivada desde filhote, pois podem se mostrar um tanto quanto impacientes em alguns casos. Trata-se de uma raça cheia de foco que pode ser dominante em algumas situações.",
    ),
    Pet(
      "Maltês",
      "Egipto",
      "condition",
      Category.DOG,
      "assets/images/dogs/maltes.png",
      false,
      "20 cm - 25 cm",
      "3Kg - 4Kg",
      "De R\$ 1.200 a R\$ 4.500",
      "Varia de 15 a 18 anos",
      "Considerado uma das raças mais antigas do mundo, o cachorro maltês foi criado no ano 500a.c. na República de Malta. Apesar de não parecer, o que muita gente não imagina é que esses cães tão lindos e aristocratas eram utilizados como rateiros, ou seja, a função inicial do maltês era de caçar ratos e outros roedores. Seu tamanho, inclusive, sempre foi excelente para tal ofício - já que era com facilidade que eles adentravam as tocas e “esconderijos” desses animais.",
    ),
    Pet(
      "Mastiff",
      "Afeganistão",
      "condition",
      Category.DOG,
      "assets/images/dogs/mastiff.png",
      false,
      "66 cm - 70 cm",
      "70Kg - 90Kg",
      "De R\$ 3.500 a R\$ 6.000",
      "Varia de 8 a 10 anos",
      "Todo tamanho do Mastiff impressiona, mas, por trás de toda grandeza, está um cachorro dócil, que precisa de muita atenção e carinho. Se os tutores precisarem de alguém para protegê-los, esses cães não hesitarão em ajudá-los. Toda a tranquilidade que eles esbanjam pode desaparecer em segundos se notarem uma briga em casa ou até mesmo que alguém que amam corre perigo. O Mastife, ou Mastim inglês, sabe usar seu grande tamanho nos momentos em que precisa ser respeitado!",
    ),
    Pet(
      "Mastim Napolitano",
      "Itália",
      "condition",
      Category.DOG,
      "assets/images/dogs/affenpinscher.png",
      false,
      "60 cm - 80 cm",
      "50Kg - 70Kg",
      "De R\$ 2.500 a R\$ 4.000",
      "Varia de 8 a 10 anos",
      "O mastim napolitano é considerado um dos cães mais antigos do mundo. Criado na Itália no ano 100a.c., ele era muito utilizado como cachorro de guarda e de briga. Enorme, ele pode atingir até 80cm de altura e pesar cerca de 70Kg. Sua pele enrugada e em excesso tem um próposito: fazer com que tivessem vantagens durante as brigas, uma vez que os adversários só tinham acesso à pele, ficando longe de órgãos e os machucando em menor intensidade. Essa vantagem nas lutas fazia, frequentemente, com que se destacassem muito nos duelos e impressionassem a todos desta forma. Fortes que são, era comum que alguns mastins fossem também usados para puxar cargas e carroças carregadas de objetos.",
    ),
    Pet(
      "Mastim Tibetano",
      "Tibet",
      "condition",
      Category.DOG,
      "assets/images/dogs/mastim_tibetano.png",
      false,
      "61 cm - 66 cm",
      "55Kg - 80Kg",
      "De R\$ 2.500 a R\$ 4.000",
      "Varia de 10 a 14 anos",
      "Quem vê um Mastim Tibetano fica facilmente encantado com sua pelagem fora do comum. Mas, além dessa característica tão marcante, o cachorro também apresenta traços como lealdade e apego ao dono. Além disso, ele é calmo e bastante independente.",
    ),
    Pet(
      "Norfolk Terrier",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/norfolk_terrier.png",
      false,
      "25 cm - 26 cm",
      "4Kg - 5Kg",
      "De R\$ 1.500 a R\$ 3.500",
      "N/A",
      "O Norfolk Terrier tem as características de seu grupo: atento, observador, caçador e curioso. Antigamente, esse cão era preparado para trabalhar em bando, caçando tudo o que lhe era pedido. Carrega em si os traços de seus semelhantes, como confiança e resistência. Mas não pense que ele é um cachorro durão, que vai estar bravo na maior parte do tempo. O cão Norfolk Terrier é muito fofo e vai adorar passar muitos momentos no colo do seu tutor recebendo carinho. Para quem procura um companheiro animado e corajoso, essa raça é ideal!",
    ),
    Pet(
      "Norwich Terrier",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/norwich_terrier.png",
      false,
      "23 cm - 25 cm",
      "4Kg - 5Kg",
      "De R\$ 2.500 a R\$ 5.000",
      "Varia de 10 a 14 anos",
      "Um dos menores Terriers é facilmente confundido com seu irmão Norfolk Terrier - a dica para não errar é prestar atenção nas orelhas, o Norwich tem elas pontiagudas que erguidas parecem um chapéu de bruxa. O pequenino é bastante ativo e já foi usado para caçar ratos e espantar raposas. É considerado uma raça rara, e bem difícil de ser encontrada, mas se você der a sorte de encontrar um, espere por encontrar um cachorro muito amoroso, divertido e brincalhão, que faz questão de estar em contato com as pessoas.",
    ),
    Pet(
      "Papillon",
      "França",
      "condition",
      Category.DOG,
      "assets/images/dogs/papillon.png",
      false,
      "27 cm - 28 cm",
      "2Kg - 5Kg",
      "De R\$ 1.800 a R\$ 4.000",
      "Varia de 12 a 17 anos",
      "Saber sobre as origens das palavras é sempre algo revelador, como no caso Papillon, cujo nome vem da palavra francesa para borboleta. O nome para definir os cães dessa raça foi uma escolha certeira, pois eles têm as orelhas eretas e franjadas que lembram muito as asas de uma borboleta, além do que são donos de muita beleza, elegância e graciosidade, assim como um dos insetos mais famosos que existe. O pequenino Papillon chega ao máximo de 28 cm, mas o que lhe falta em tamanho sobra em alegria, inteligência e amor à família. Seus olhos grandes vão ficar sempre atentos aos seus movimentos e também ao que está acontecendo ao redor. Ele é vigilante a todo momento.",
    ),
    Pet(
      "Pastor Alemão",
      "Alemanha",
      "condition",
      Category.DOG,
      "assets/images/dogs/pastor_alemao.png",
      false,
      "55 cm - 65 cm",
      "22Kg - 44Kg",
      "De R\$ 1.500 a R\$ 5.000",
      "Varia de 10 a 14 anos",
      "Como o próprio nome já diz, a raça Pastor Alemão é originária da Alemanha e os antecessores dessa raça são datados do século XII. A partir do século XIX um oficial da cavalaria chamado Max von Stephantiz decidiu utilizar sua aposentadoria para criar uma raça uniforme e de excelência. Seu objetivo era juntar todas as melhores características dos cães pastores existentes pelas diversas regiões da Alemanha a fim de chegar a uma raça perfeita. Seu objetivo foi alcançado com louvor e hoje o Pastor Alemão é uma das raças mais conhecidos e apreciadas no mundo todo! Mesmo tendo ganhado o mundo rapidamente, na época da Primeira Guerra Mundial qualquer coisa que remetesse aos alemães era estigmatizada, por isso nessa época o American Kennel Club mudou o nome da raça de Pastor Alemão para Cão Pastor e na Inglaterra ele passou a ser chamado de Lobo da Alsácia. No entanto em 1921, o AKC retomou o nome Pastor Alemão, mas na Inglaterra ele só voltou a ser chamado assim em 1977. Após esse evento, cachorros da raça Pastor Alemão ficaram ainda mais famosos. Os diversos aparecimentos na TV e no cinema, principalmente com Rin Tin Tin, um Pastor Alemão astro do seu próprio programa de televisão, fizeram deles exemplares muito almejados.",
    ),
    Pet(
      "Pastor Australiano",
      "Estados Unidos",
      "condition",
      Category.DOG,
      "assets/images/dogs/pastor_australiano.png",
      false,
      "46 cm - 58 cm",
      "20Kg - 25Kg",
      "De R\$ 2.000 a R\$ 6.000",
      "Varia de 12 a 16 anos",
      "Muito confundido com o border collie, o pastor australiano possui como particularidade a ausência de rabo. Diferentemente do que muitos pensam, esta raça não é submetida à caudectomia (cirurgia para corte do rabo), mas já nasce com um rabinho mais curto do que o habitual. Bastante ativo e brincalhão, este cão de pastoreio vem ganhando destaque no meio urbano por sua inteligência e lealdade. Facilmente adestrável, o cão pastor australiano requer atividades físicas e mentais frequentes para que não fique entediado e nem se torne destruidor. Também chamados de “aussies” em algumas partes do Mundo, acredita-se que os pastores australianos tenham este nome por terem passado pela Austrália antes de chegarem aos Estados Unidos e não por terem sido criados por lá. Criados no século XIX, eles até hoje são muito usados como cachorros de pastoreio, participando inclusive de competições em diversas partes do mundo. Costumam ser cães dóceis com o rebanho, não sendo difíceis de serem adestrados para a função. Em alguns países, são famosos como cães de busca e salvamento, embora não sejam tão grandes fisicamente para tal atividade (como os são bernardos, por exemplo).",
    ),
    Pet(
      "Pinscher Miniatura",
      "Alemanha",
      "condition",
      Category.DOG,
      "assets/images/dogs/pinscher_miniatura.png",
      false,
      "25 cm - 30 cm",
      "4Kg - 6Kg",
      "De R\$ 1.500 a R\$ 2.000",
      "Varia de 12 a 15 anos",
      "'50% ódio, 50% tremedeira'. Já ouviu essa expressão antes? Apesar da fama de estressado, o Pinscher é um cão muito companheiro e que conquistou uma legião de fãs mundo afora. A história do surgimento da raça é incerta. Muita gente acha que eles são descendentes do Doberman, mas os Pinschers surgiram bem antes. Registros provam sua origem na Alemanha há cerca de duzentos anos, mas pinturas e registros bem mais antigos retratam cães muito parecidos com a raça, o que deixa a origem desses cachorros em dúvida. Resultado do cruzamento de alguns terriers, do Dachshund e do Greyhound, o Min Pin, como também é conhecido, foi registrado no American Kennel Club em 1925 e é uma raça muito popular aqui no Brasil.",
    ),
    Pet(
      "Poodle",
      "França",
      "condition",
      Category.DOG,
      "assets/images/dogs/poodle.png",
      false,
      "25 cm - 60 cm",
      "2Kg - 23Kg",
      "De R\$ 1.000 a R\$ 4.000",
      "Varia de 14 a 18 anos",
      "Uma das raças mais conhecidas no mundo todo, o Poodle possui diversas características que faz com sejam amados por todos. Sua história, no entanto, é um pouco incerta. Sua origem oficial é na França, mas muitos pesquisadores afirmam que a raça surgiu primeiro na Alemanha (sabe-se que o primeiro poodle, o poodle gigante, é de lá). Um indício é o nome, já que Poodle vem de pfudel, uma palavra alemã que significa “poça” exaltando uma das principais características da raça já que esses cães são exímios nadadores e adoram uma brincadeira com água. A tosa da raça também é motivo de divergência. O corte “leão” era feito para que os cães possuíssem maior desempenho na água, na caça de aves aquáticas (prática que desempenhavam na França). Nessa tosa as partes mais sensíveis a baixas temperaturas (como tórax, principalmente) possuíam maior quantidade de pelos. Em contrapartida, alguns afirmam que a tosa era utilizada na Alemanha para auxiliar na prática do pastoreio, já que sua semelhança com a pelagem de um leão servia para espantar os lobos. Seja como for, o que se tem certeza é que o Poodle é um cão bem antigo. Inúmeros registros retratam esse cachorro seja em pinturas ou esculturas existentes há mais de 400 anos, mas foi em 1887 que a raça passou a ser reconhecida pelo American Kennel Club.",
    ),
    Pet(
      "Pug",
      "China",
      "condition",
      Category.DOG,
      "assets/images/dogs/pug.png",
      true,
      "35 cm - 40 cm",
      "6Kg - 8Kg",
      "De R\$ 2.000 a R\$ 5.000",
      "Varia de 12 a 14 anos",
      "Essa raça é uma das mais antigas que existe. Foram encontrados indícios de cachorros muito parecidos com o Pug datados de 1700 antes de Cristo! No entanto, não se tem certeza absoluta de sua origem. Existem teorias de que o Pug surgiu do cruzamento de diversas outras raças como o Pequinês ou ainda o Mastife Francês. O que se tem certeza é de que os Pugs surgiram em algum local da China e eram cachorros pertencentes à realeza. Esses cãezinhos foram levados para a Holanda e a partir de lá atingiram outros países da Europa onde receberam diferentes nomes. Na França ficaram conhecidos como 'Carlin', na Espanha como 'Dugollo', na Alemanha eram os 'Mops' e na Itália eram chamados de 'Caganlino'. Os Pugs chegaram aos EUA após a Guerra Civil e foram reconhecidos como raça oficial pelo Kennel Club em 1885.",
    ),
    Pet(
      "Rottweiler",
      "Alemanha",
      "condition",
      Category.DOG,
      "assets/images/dogs/rottweiler.png",
      false,
      "56 cm - 68 cm",
      "46Kg - 50Kg",
      "De R\$ 2.000 a R\$ 6.000",
      "Varia de 8 a 10 anos",
      "Eles são grandes, fortes e apesar da cara de mau são cães muito amorosos e extremamente apegados aos seus humanos. Trata-se de uma raça muito antiga, afinal os antecessores dos Rottweilers acompanhavam as legiões romanas pelos longos caminhos que percorriam. Uma das paradas obrigatórias dos soldados ficava do sul da Alemanha, um centro comercial e administrativo muito importante que se desenvolveu ainda mais com a presença dos romanos. Os prédios mais importantes receberam telhas vermelhas e a região passou a ser conhecida como Rottwill que significa vila vermelha. Com o tempo, o nome mudou para Rottweil. como é conhecida até hoje. Daí surgiu o nome da raça Rottweiler. Por volta de 250d.c., os romanos foram expulsos da região por tribos locais e muitos dos cães foram deixados para trás, a população passou então a criá-los. O cachorro Rottweiler chegou à América em 1928 e foi registrado pelo American Kennel Club em 1931.",
    ),
    Pet(
      "Sem Raça Definida (SRD)",
      "Desconhecido",
      "condition",
      Category.DOG,
      "assets/images/dogs/sem_raca_definida_srd.png",
      false,
      "N/D",
      "N/D",
      "N/D",
      "N/D",
      "Simplesmente o cachorro mais popular do Brasil! O termo SRD (Sem Raça Definida) abrange todos os cachorros que não possuem origem definida, com misturas em sua linhagem de duas ou mais raças. Um verdadeiro testamento à natureza, a um tempo em que os animais procriavam sem a interferência do homem, pode-se dizer que esse é o primeiro cachorro do mundo a surgir do lobo.",
    ),
    Pet(
      "Shih Tzu",
      "Tibet",
      "condition",
      Category.DOG,
      "assets/images/dogs/shih_tzu.png",
      false,
      "20 cm - 26 cm",
      "4Kg - 8Kg",
      "De R\$ 1.200 a R\$ 3.500",
      "Varia de 10 a 18 anos",
      "Focinho achatado, olhos amendoados um pouco saltados e personalidade marcante: este é o Shih Tzu! Conhecidos por serem muito companheiros, os Shih Tzus não são cães de caça ou esportistas, o propósito de suas vidas é amar e ser amado pelos seus pais humanos, servindo como um incrível cão de companhia. Sempre prontos para receber carinho, são muito dóceis e amigáveis com crianças e outros cães. Definitivamente eles são cachorros de ambientes internos e se adaptam muito bem a apartamentos por serem pequenos e não precisarem de muito espaço para se movimentar, porém, isso não exclui a necessidade de exercícios físicos regulares. Os Shih Tzus se adaptam muito bem a diferentes “tipos de tutores”, quando você quiser caminhar eles estarão ao seu lado, ou, quando quiser tirar uma soneca, também estarão, como sempre fizeram desde que surgiram.",
    ),
    Pet(
      "Silky Terrier",
      "Austrália",
      "condition",
      Category.DOG,
      "assets/images/dogs/silky_terrier.png",
      false,
      "23 cm - 26 cm",
      "3Kg - 4Kg",
      "De R\$ 1.500 a R\$ 3.000",
      "Varia de 12 a 15 anos",
      "Criado para ser cão de companhia na Austrália, no século XIX, o Silky Terrier Australiano se parece bastante com o yorkshire terrier, de quem descende. A diferença principal entre eles está na coloração dos pelos (os silkyes possuem um tom mais prateado ao invés de preto) e no aspecto dos mesmos, que em alguns casos podem parecer mais encaracolados do que lisos.",
    ),
    Pet(
      "Skye Terrier",
      "paReino Unidois",
      "condition",
      Category.DOG,
      "assets/images/dogs/skye_terrier.png",
      false,
      "25 cm - 26 cm",
      "10Kg - 12Kg",
      "De R\$ 2.000 a R\$ 4.500",
      "Varia de 12 a 14 anos",
      "Este terrier de porte médio e corpo alongado foi desenvolvido na Escócia para caçar raposas, texugos e lontras. Hoje, por conta de sua versatilidade, também pode ser utilizado como um cão de guarda, apesar de seu porte pouco avantajado. Sempre alerta, é um cachorro destemido, amigável, feliz e, com certeza, uma excelente escolha para quem vive em apartamento. Bastante dócil, o peludinho tem todos os predicados para fazer a sua vida mais divertida e feliz.",
    ),
    Pet(
      "Staffordshire Bull Terrier",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/staffordshire_bull_terrier.png",
      false,
      "35 cm - 40 cm",
      "11Kg - 17Kg",
      "De R\$ 2.000 a R\$ 4.000",
      "Varia de 8 a 12 anos",
      "Esse Terrier natural de Staffordshire, na Inglaterra, ama sua família, se dá muito bem com humanos e já foi conhecido como o “cachorro babá”, devido a sua docilidade e paciência com crianças. Não se deixe levar pela reputação dos Pit Bulls, quando o assunto são humanos, os Staffies realmente são muito apaixonados por nós. A convivência se torna  problemática quando o assunto são outros cães, traço esse ainda remanescente de sua origem nos ringues. Por isso, esse relacionamento deve ser trabalhado no cão através de socialização e treinamento desde filhote para que se acostume com a presença dos outros animais. Eles são particularmente abertos com estranhos. Adoram um bom jogo e desafios, então essa também é uma boa alternativa para drenar toda essa energia que os Staffies têm.",
    ),
    Pet(
      "Terra Nova",
      "Canadá",
      "condition",
      Category.DOG,
      "assets/images/dogs/terra_nova.png",
      false,
      "66 cm - 71 cm",
      "54Kg - 68Kg",
      "De R\$ 2.500 a R\$ 5.500",
      "Varia de 8 a 10 anos",
      "Eles são grandões, peludos, dóceis e fofos demais! Apesar de serem pouco comuns aqui no Brasil, cães da raça Terra Nova tem um lugar de respeito na história sendo considerada uma das raças com a maior habilidade dentro da água. Eles originaram em uma Ilha Canadense de nome Newfoundland (Terra Nova). Seus ancestrais eram cães indígenas, além do grande-cão-urso-preto que foram trazidos até a região por Vikings em algum momento após o ano de 1100. Esses adoráveis cães tornaram-se grandes companheiros dos pescadores da região, além de auxiliarem nas tarefas, já que nadar era o ponto forte. Quando pescadores vieram da Europa, outras raças foram cruzadas com os cães que já estavam instalados na ilha. Cachorros como o Labrador Retriever e o São Bernardo ajudaram a deixar a raça Terra Nova ainda mais forte e característica. Sendo assim, em 1610 quando a ilha Newfoundland foi colonizada, esses cães já estavam completamente instalados e definidos como uma raça uniforme. Foi em 1886 que a raça Terra nova foi registrada oficialmente pelo American Kennel Club.",
    ),
    Pet(
      "Terrier Escocês",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/terrier_escoces.png",
      false,
      "25 cm - 28 cm",
      "8Kg - 10Kg",
      "De R\$ 2.000 a R\$ 3.200",
      "Varia de 11 a 13 anos",
      "Criado no Reino Unido no século XIX, o terrier escocês (mundialmente conhecido como scottish terrier) é um simpático cachorro de caça que por seu tamanho reduzido e postura atlética ganhou também espaço dentro dos lares de diversos lugares do mundo. Sua cabeça em forma de martelo e barba comprida chamam a atenção de quem não conhece sobre a raça. Com apenas 25cm de altura e no máximo 10Kg, o scottish terrier costuma ser destemido e cheio de vida - algo que faz com que seja considerado único por quem tem um exemplar por perto. Em pode ser confundido com o schnauzer, embora sejam um tanto quanto diferentes, de maneira geral.",
    ),
    Pet(
      "Tosa",
      "Japão",
      "condition",
      Category.DOG,
      "assets/images/dogs/tosa.png",
      false,
      "55 cm - 60 cm",
      "45Kg - 90Kg",
      "De R\$ 2.000 a R\$ 4.000",
      "Varia de 10 a 12 anos",
      "O maior cachorro de origem japonesa, o Tosa não é uma raça indicada para tutores caninos inexperientes. Mesmo sendo calmo, confiante e paciente, ele não é o cachorro mais fácil de se viver e precisa de adestramento firme, de preferência começando ainda quando filhote, principalmente para socializá-lo com outros cães, já que tem a tendência a ser dominante e particularmente agressivo com cachorros do mesmo sexo, e com estranhos, se mostrando desconfiado. Ele precisa de um líder que o guie com consistencia e confiança, mas nunca e sob nenhuma hipótese utilizando a força ou crueldade. O ideal é que ele seja exposto o quanto antes a pessoas e outros animais, dessa maneira evitando que ele se torne desconfiado.",
    ),
    Pet(
      "Weimaraner",
      "Alemanha",
      "condition",
      Category.DOG,
      "assets/images/dogs/weimaraner.png",
      false,
      "57 cm - 70 cm",
      "25Kg - 40Kg",
      "De R\$ 1.200 a R\$ 3.500",
      "Varia de 12 a 15 anos",
      "Criado no século XVII na Alemanha, o weimaraner é um cachorro tipicamente de caça e tiro. Por muito tempo, a raça foi conhecida como 'pointer de Weimar' ou 'braco de weimar' e se destacava como um excelente farejador, além de ótimo em apontar e buscar presas. Com a queda da popularidade da caça no mundo todo, este cachorro passou a ser usado frequentemente para guarda, mas também para companhia em alguns casos. Alertas e sempre atentos ao que acontece ao redor, os weimaraners possuem bastante energia e resistência, por isso é um dos cães de trabalho favoritos em diferentes países do mundo. Seu corpo forte e pelo brilhante chamam a atenção por onde passam. Costumam ser cães um pouco reservado com estranhos e podem se mostrar um tanto quanto dominantes em algumas situações.",
    ),
    Pet(
      "Welsh Corgi",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/welsh_corgi.png",
      false,
      "25 cm - 30 cm",
      "9Kg - 12Kg",
      "De R\$ 3.000 a R\$ 5.000",
      "Varia de 12 a 14 anos",
      "Conhecido no mundo inteiro como o “cão da rainha”, o Pembroke Welsh Corgi chama a atenção por suas orelhas bem compridas e seu rabo quase que ausente. Curioso e forte, este cãozinho de patas curtas costuma ser destemido e bastante ativo, com um latido surpreendente. Criado para pastorear gados no século XI, o corgi ganhou popularidade por ser a raça favorita da Rainha Elizabeth II, quem até hoje frequentemente aparece acompanhada de pelo menos um exemplar da raça.",
    ),
    Pet(
      "West Highland White Terrier",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/west_highland_white_terrier.png",
      false,
      "28 cm - 30 cm",
      "6Kg - 8Kg",
      "De R\$ 1.500 a R\$ 4.000",
      "Varia de 15 a 20 anos",
      "Simpáticos demais, a raça West Highland White Terrier é conhecida simplesmente como Westie por seus adoradores. A raça é originária da Escócia e compartilhava lugar com outros terriers como o Cairn Terrier, o Terrier Escocês, Skye e o Dandie Dinmont. Todos foram considerados uma única raça por algum tempo. Mas foi no ano de 1840 que um apreciador desses cães estava caçando quando acidentalmente atirou contra um de seus cachorros de cor avermelhada, confundindo-o com uma raposa. Após esse episódio triste, o coronel Malcon deu início a uma criação de cães exclusivamente brancos e assim nasceu o West Highland White Terrier. Em 1908, ele foi registrado oficialmente pelo American Kennel Club.",
    ),
    Pet(
      "Whippet",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/whippet.png",
      false,
      "44 cm - 51 cm",
      "10Kg - 13Kg",
      "De R\$ 1.200 a R\$ 2.000",
      "Varia de 12 a 15 anos",
      "Criado no século XIX, na Grã-Bretanha, o whippet se parece muito com o greyhound, mas é bem menor do que ele. Pesando aproximadamente 13Kg e medindo 40cm, este pequeno corredor tem ganhado espaço em diversas partes do mundo. Muitos criadores acreditam que a raça seja um resultado de cruzamentos entre o greyhound (galgo), alguns terriers e o pequeno lebreu italiano (menor cão de corrida oficialmente reconhecido).",
    ),
    Pet(
      "Xoloitzcuintli",
      "México",
      "condition",
      Category.DOG,
      "assets/images/dogs/xoloitzcuintli.png",
      false,
      "25 cm - 55 cm",
      "4Kg - 12Kg",
      "De R\$ 1.600 a R\$ 4.000",
      "Varia de 12 a 14 anos",
      "Com um nome nada fácil de pronunciar, o Xoloitzquintli não nos deixa outra alternativa a não ser utilizar seus outros nomes. Apesar de não ser muito difundido mundialmente, o também conhecido como Cão sem pelos mexicano ou Pelado Mexicano não só é bastante conhecido em seu país de origem, o México, como também é visto como um tesouro nacional para a população local. Com origem pré-colombiana, há cerca de mais de 3.500 anos e natural da Mesoamérica, o Xolo é a primeira raça canina das américas. Na época considerado um profeta e guia no submundo, os povos locais acreditavam que ele guiaria as almas dos astecas no além.",
    ),
    Pet(
      "Yorkshire Terrier",
      "Reino Unido",
      "condition",
      Category.DOG,
      "assets/images/dogs/yorkshire_terrier.png",
      false,
      "20 cm - 22 cm",
      "2Kg - 4Kg",
      "De R\$ 1.200 a R\$ 5.000",
      "Varia de 12 a 16 anos",
      "O Yorkshire surgiu na cidade de mesmo nome na Inglaterra por volta do ano de 1800. Acredita-se que a raça tenha sido criada por camponeses para auxiliar na caça de roedores (já que o seu tamanho permitia fácil acesso às tocas). Através do cruzamento de diversos outros Terriers e também do Maltês, surgiram os Yorkshire Terriers. Por volta de 1880 a raça chegou à América, porém a diversidade de tamanhos gerou certa confusão e foi só em 1900 que chegou-se a um acordo, ficando decidido que o cachorro de menor tamanho seria considerado o padrão da raça. Hoje em dia o Yorkshire é um cãozinho muito popular no mundo todo e, ironicamente, encontrado em diferentes tamanhos.",
    ),
  ];
}
